name: Check health

on:
  schedule:
    - cron: '0 2 * * * '

jobs:
  health-check:
    runs-on: ubuntu-18.04
    steps:
    - name: check health
      uses: jtalk/url-health-check-action@v1.2
      with:
        url: "https://full-stack-open-pokemon.herokuapp.com/health"
        max-attempts: 3 
        retry-delay: 5s 