name: Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.8.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "full-stack-open-pokemon"
        heroku_email: "tikker.laura@gmail.com"
        healthcheck: "https://full-stack-open-pokemon.herokuapp.com/health"
        checkstring: "wrong string"
        delay: 5